version: '3'
services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: shppmydb
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    networks:
      - my-network
    mem_limit: 1024m
    mem_reservation: 512m

  app:
    image: 4docker
    container_name: 4docker
    ports:
      - 4000:4000
    build: .
    networks:
      - my-network
    mem_limit: 256m
    mem_reservation: 128m

networks:
  my-network:
    driver: bridge
